Add oacd start

diff --git a/oacd b/oacd
--- a/oacd
+++ b/oacd
@@ -7,6 +7,60 @@ ENABLED_PLUGINS_FILE=$BASEDIR/enabled_plugins
 ULON="\033[4m"
 ULOFF="\033[0m"
 
+start()
+{
+	ERL=erl
+	NAME="openacd@127.0.0.1"
+	COOKIE=oucxdevcookie
+
+	RUNDIR="$BASEDIR"/run
+	DBDIR="$RUNDIR"/db
+	LOGDIR="$RUNDIR"/log
+	ENABLED_PLUGINS="$BASEDIR"/enabled_plugins
+
+	KEY="$RUNDIR"/key
+	SYSCONFIG="$RUNDIR"/etc/sys.config
+
+	export ERL_CRASH_DUMP="$LOGDIR"/erlang_crash.dump
+
+	mkdir -p "$RUNDIR"
+	mkdir -p "$DBDIR"
+	mkdir -p "$LOGDIR"
+
+	export OPENACD_RUN_DIR="$RUNDIR"
+
+	if [ ! -f "$KEY" ]; then
+		echo "RSA key does not exist, generating..."
+		ssh-keygen -t rsa -f "$KEY" -N ""
+		RES=$?
+		if [ $RES != 0 ]; then
+			echo "Key generation failed with error $RES!"
+			exit $RES
+		fi
+	fi
+
+	if [ ! -f "$SYSCONFIG" ]; then
+		mkdir -p `dirname $SYSCONFIG`
+
+		CONFIGNODENAME=`erl -eval "io:format(\"~s\",[node()]),halt(1)" -name $NAME -noshell`
+		cat > "$SYSCONFIG" <<EOF
+[{'oacd_core', [
+	{nodes, ['$CONFIGNODENAME']}
+	, {console_loglevel, info}
+	, {logfiles, [{"$LOGDIR/openacd.log", debug}]}
+	, {plugins, [`awk 'BEGIN{OFS=",";RS=""}{$1=$1}1' $ENABLED_PLUGINS`]}
+]},
+{sasl, [
+	{errlog_type, error} % disable SASL progress reports
+]}].
+EOF
+
+	fi
+
+	export ERL_LIBS="$BASEDIR"/deps:"$BASEDIR"/core:"$BASEDIR"/oacd_plugins:$ERL_LIBS
+	exec erl -s openacd -config "$SYSCONFIG" -name "$NAME" -mnesia dir \""$DBDIR"\"
+}
+
 add_plugin()
 {
 	PLUGIN=$1
@@ -47,6 +101,9 @@ disable_plugin()
 usage()
 {
 	echo "List of commands"
+	echo ""
+	echo "  start"
+	echo ""
 	echo -e "  add-plugin ${ULON}name${ULOFF} ${ULON}git-repo${ULOFF}"
 	echo -e "  create-plugin ${ULON}name${ULOFF}"
 	echo -e "  disable-plugin ${ULON}name${ULOFF}"
@@ -59,5 +116,6 @@ case $* in
 	'create-plugin') create_plugin $2;;
 	'enable-plugin') enable_plugin $2;;
 	'disable-plugin') disable_plugin $2;;
+	'start') start;;
 	*) usage;;
 esac
