Add openacd start, live

diff --git a/templates/scripts/openacd b/templates/scripts/openacd
--- a/templates/scripts/openacd
+++ b/templates/scripts/openacd
@@ -3,292 +3,201 @@
 # ex: ts=4 sw=4 et
 
 RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
-
-CALLER_DIR=$PWD
-
-RUNNER_BASE_DIR=${RUNNER_SCRIPT_DIR%/*}
-RUNNER_ETC_DIR=etc/openacd
-# Note the trailing slash on $PIPE_DIR/
-PIPE_DIR=/tmp/$RUNNER_BASE_DIR/
-RUNNER_USER=
+RUNNER_USER=%RUNNER_USER%
 
 # Make sure this script is running as the appropriate user
 if [ ! -z "$RUNNER_USER" ] && [ `whoami` != "$RUNNER_USER" ]; then
     exec sudo -u $RUNNER_USER -i $0 $@
 fi
 
-# Identify the script name
-SCRIPT=`basename $0`
+# erlang binaries
+ERL=erl
+ESCRIPT=escript
 
-# Parse out release and erts info
-# START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
-ERTS_VSN=${START_ERL% *}
-APP_VSN=${START_ERL#* }
+# erlang options
+ERL_POLL=true
+ERL_SMP=auto
+ERL_NODE=openacd
+ERL_HOST=$(hostname -f)
+ERL_COOKIE=
 
-# Use $CWD/env.config if exists, otherwise releases/APP_VSN/env.config, or else etc/env.config
-if [ -e "$CALLER_DIR/env.config" ]; then
-    VMARGS_PATH=$CALLER_DIR/env.config
-    USE_DIR=$CALLER_DIR
-else
-    USE_DIR=$RUNNER_BASE_DIR
-    if [ -e "$RUNNER_BASE_DIR/releases/$APP_VSN/env.config" ]; then
-        VMARGS_PATH="$RUNNER_BASE_DIR/releases/$APP_VSN/env.config"
-    else
-        VMARGS_PATH="$RUNNER_ETC_DIR/env.config"
-    fi
+# other vm args
+ERL_ARGS=
+
+# pipe dir - must end with '/'
+PIPE_DIR=/tmp/openacd/
+
+# system configured dirs
+BIN_DIR=%BIN_DIR%
+ETC_DIR=%SYSCONFIG_DIR%
+VAR_DIR=%LOCALSTATE_DIR%
+LIB_DIR=%LIB_DIR%
+
+OA_LIB_DIR=$LIB_DIR/openacd
+OA_ETC_DIR=$ETC_DIR/openacd
+
+OA_LOG_DIR=$VAR_DIR/log/openacd
+OA_DB_DIR=$VAR_DIR/openacd/db
+OA_CORE_DIR=$LIB_DIR/openacd/core
+OA_PLUGIN_DIR=$LIB_DIR/openacd/plugins
+
+ARGS=
+while [ "$#" -ne 0 ]; do
+    PARAM=$1
+    shift
+    case $PARAM in
+        --) break ;;
+        --config-dir) OA_ETC_DIR=$1 ; shift ;;
+        --env-config) OA_ENV_CONFIG_PATH=$1 ; shift ;;
+        --config) OA_CONFIG_CTL_PATH=$1 ; shift ;;
+        *) ARGS="$ARGS $PARAM" ;;
+    esac
+done
+
+# paths
+: ${OA_ENV_CONFIG_PATH:=$OA_ETC_DIR/env.config}
+: ${OA_CONFIG_PATH:=$OA_ETC_DIR/sys.config}
+
+# run env config
+[ -f "$OA_ENV_CONFIG_PATH" ] && . "$OA_ENV_CONFIG_PATH"
+
+# command line config path overrides
+if [ ! -z "$OA_CONFIG_CTL_PATH" ]; then
+    OA_CONFIG_PATH=$OA_CONFIG_CTL_PATH
 fi
 
-RUNNER_LOG_DIR=$USE_DIR/log
-# Make sure log directory exists
-mkdir -p $RUNNER_LOG_DIR
+# name
+: ${ERL_NAME:=$ERL_NODE@$ERL_HOST}
+ERL_NAME_TYPE=-name
+# long or short names
+if [ "$ERL_HOST" = "${ERL_HOST%.*}" ]; then
+    ERL_NAME_TYPE=-sname
+fi
+ERL_NAME_ARG="$ERL_NAME_TYPE $ERL_NAME"
 
-# Use releases/VSN/sys.config if it exists otherwise use etc/app.config
-if [ -e "$USE_DIR/sys.config" ]; then
-    CONFIG_PATH="$USE_DIR/sys.config"
-else
-    if [ -e "$RUNNER_BASE_DIR/releases/$APP_VSN/sys.config" ]; then
-        CONFIG_PATH="$RUNNER_BASE_DIR/releases/$APP_VSN/sys.config"
-    else
-        CONFIG_PATH="$RUNNER_ETC_DIR/app.config"
-    fi
+# cookie
+ERL_COOKIE_ARG=
+if [ ! -z "$ERL_COOKIE" ]; then
+    ERL_COOKIE_ARG="-setcookie \'$ERL_COOKIE\'"
 fi
 
-# Extract the target node name from node.args
-NAME_ARG=`egrep '^-s?name' $VMARGS_PATH`
-if [ -z "$NAME_ARG" ]; then
-    echo "env.config needs to have either -name or -sname parameter."
-    exit 1
-fi
+# logs
+[ -d "$OA_LOG_DIR" ] || mkdir -p "$OA_LOG_DIR"
+DATETIME=`date "+%Y%m%d-%H%M%S"`
+ERL_CRASH_DUMP=$OA_LOG_DIR/erl_crash_$DATETIME.dump
 
-# Extract the name type and name from the NAME_ARG for REMSH
-REMSH_TYPE=`echo $NAME_ARG | awk '{print $1}'`
-REMSH_NAME=`echo $NAME_ARG | awk '{print $2}'`
+# db
+[ -d "$OA_DB_DIR" ] || mkdir -p "$OA_DB_DIR"
+
+# plugins
+[ -d "$OA_PLUGIN_DIR" ] || mkdir -p "$OA_PLUGIN_DIR"
+
+# home
+HOME=$VAR_DIR/openacd
+[ -d "$HOME" ] || mkdir -p "$HOME"
+
+# path
+ERL_LIBS=$ERL_LIBS:$OA_CORE_DIR:$OA_PLUGIN_DIR
+
+cd $HOME
+
+# export globals
+export HOME
+export ERL_CRASH_DUMP
+export ERL_LIBS
+
+# set-up nodetool
+NODETOOL_PATH=$OA_LIB_DIR/bin/nodetool
+NODETOOL="$ESCRIPT $NODETOOL_PATH"
 
 # Note the `date +%s`, used to allow multiple remsh to the same node transparently
 REMSH_NAME_ARG="$REMSH_TYPE remsh`date +%s`@`echo $REMSH_NAME | awk -F@ '{print $2}'`"
 REMSH_REMSH_ARG="-remsh $REMSH_NAME"
 
-# Extract the target cookie
-COOKIE_ARG=`grep '^-setcookie' $VMARGS_PATH`
-if [ -z "$COOKIE_ARG" ]; then
-    echo "env.config needs to have a -setcookie parameter."
-    exit 1
-fi
+START_CMD="$ERL \
+    $ERL_NAME_ARG \
+    $ERL_COOKIE_ARG \
+    -s openacd \
+    -config $OA_CONFIG_PATH \
+    -mnesia dir \"\\\"$OA_DB_DIR\\\"\"
+    -detached \
+    $ERL_OPTS"
 
-# Make sure CWD is set to the right dir
-cd $USE_DIR
+status ()
+{
+    echo "status"
+}
 
-# Make sure log directory exists
-mkdir -p $USE_DIR/log
+start()
+{
+    checkdupname
+    checkstorage
 
+    ERL_CMD="$ERL \
+        $ERL_NAME_ARG \
+        $ERL_COOKIE_ARG \
+        -s openacd \
+        -config $OA_CONFIG_PATH \
+        -mnesia dir \"$OA_DB_DIR\"\
+        -detached \
+        $ERL_OPTS"
+}
 
-# Add ERTS bin dir to our path
-ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin
+live()
+{
+    checkdupname
+    checkstorage
 
-# Setup command to control the node
-NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME_ARG $COOKIE_ARG"
+    ERL_CMD="$ERL \
+        $ERL_NAME_ARG \
+        $ERL_COOKIE_ARG \
+        -config $OA_CONFIG_PATH \
+        -mnesia dir \"$OA_DB_DIR\"\
+        $ERL_OPTS"
+    exec $ERL_CMD
+}
 
-# Setup remote shell command to control node
-REMSH="$ERTS_PATH/erl $REMSH_NAME_ARG $REMSH_REMSH_ARG $COOKIE_ARG"
+usage()
+{
+    echo "Usage: $0 start|live|status|stop"
+    exit
+}
 
-# Check the first argument for instructions
-case "$1" in
-    start|start_boot)
-        # Make sure there is not already a node running
-        RES=`$NODETOOL ping`
-        if [ "$RES" = "pong" ]; then
-            echo "Node is already running!"
-            exit 1
-        fi
-        case "$1" in
-            start)
-                shift
-                START_OPTION="console"
-                HEART_OPTION="start"
-                ;;
-            start_boot)
-                shift
-                START_OPTION="console_boot"
-                HEART_OPTION="start_boot"
-                ;;
-        esac
-        RUN_PARAM=$(printf "\'%s\' " "$@")
-        HEART_COMMAND="$RUNNER_BASE_DIR/bin/$SCRIPT $HEART_OPTION $RUN_PARAM"
-        export HEART_COMMAND
-        mkdir -p $PIPE_DIR
-        $ERTS_PATH/run_erl -daemon $PIPE_DIR $RUNNER_LOG_DIR "exec $RUNNER_BASE_DIR/bin/$SCRIPT $START_OPTION $RUN_PARAM" 2>&1
-        ;;
-
-    stop)
-        # Wait for the node to completely stop...
-        case `uname -s` in
-            Linux|Darwin|FreeBSD|DragonFly|NetBSD|OpenBSD)
-                # PID COMMAND
-                PID=`ps ax -o pid= -o command=|\
-                    grep "$RUNNER_BASE_DIR/.*/[b]eam"|awk '{print $1}'`
-                ;;
-            SunOS)
-                # PID COMMAND
-                PID=`ps -ef -o pid= -o args=|\
-                    grep "$RUNNER_BASE_DIR/.*/[b]eam"|awk '{print $1}'`
-                ;;
-            CYGWIN*)
-                # UID PID PPID TTY STIME COMMAND
-                PID=`ps -efW|grep "$RUNNER_BASE_DIR/.*/[b]eam"|awk '{print $2}'`
-                ;;
-        esac
-        $NODETOOL stop
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
-        while `kill -0 $PID 2>/dev/null`;
-        do
-            sleep 1
-        done
-        ;;
-
-    restart)
-        ## Restart the VM without exiting the process
-        $NODETOOL restart
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
-        ;;
-
-    reboot)
-        ## Restart the VM completely (uses heart to restart it)
-        $NODETOOL reboot
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
-        ;;
-
-    ping)
-        ## See if the VM is alive
-        $NODETOOL ping
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            exit $ES
-        fi
-        ;;
-
-    attach)
-        # Make sure a node IS running
-        RES=`$NODETOOL ping`
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            echo "Node is not running!"
-            exit $ES
-        fi
-
-        shift
-        exec $ERTS_PATH/to_erl $PIPE_DIR
-        ;;
-
-    remote_console)
-        # Make sure a node IS running
-        RES=`$NODETOOL ping`
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            echo "Node is not running!"
-            exit $ES
-        fi
-
-        shift
-        exec $REMSH
-        ;;
-
-    upgrade)
-        if [ -z "$2" ]; then
-            echo "Missing upgrade package argument"
-            echo "Usage: $SCRIPT upgrade {package base name}"
-            echo "NOTE {package base name} MUST NOT include the .tar.gz suffix"
-            exit 1
-        fi
-
-        # Make sure a node IS running
-        RES=`$NODETOOL ping`
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            echo "Node is not running!"
-            exit $ES
-        fi
-
-        node_name=`echo $NAME_ARG | awk '{print $2}'`
-        erlang_cookie=`echo $COOKIE_ARG | awk '{print $2}'`
-
-        $ERTS_PATH/escript $RUNNER_BASE_DIR/bin/install_upgrade.escript $node_name $erlang_cookie $2
-        ;;
-
-    console|console_clean|console_boot)
-        # .boot file typically just $SCRIPT (ie, the app name)
-        # however, for debugging, sometimes start_clean.boot is useful.
-        # For e.g. 'setup', one may even want to name another boot script.
-        case "$1" in
-            console)        BOOTFILE=$SCRIPT ;;
-            console_clean)  BOOTFILE=start_clean ;;
-            console_boot)
-                shift
-                BOOTFILE="$1"
-                shift
-                ;;
-        esac
-        # Setup beam-required vars
-        ROOTDIR=$RUNNER_BASE_DIR
-        BINDIR=$ROOTDIR/erts-$ERTS_VSN/bin
-        EMU=beam
-        PROGNAME=`echo $0 | sed 's/.*\\///'`
-        CMD="$BINDIR/erlexec -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$BOOTFILE -mode embedded -config $CONFIG_PATH -args_file $VMARGS_PATH"
-        # ERL_LIBS=$ROOTDIR/lib
-        # CMD="erl -s openacd -config $CONFIG_PATH -args_file $VMARGS_PATH"
-        export EMU
-        export ROOTDIR
-        export BINDIR
-        export PROGNAME
-
-        # Dump environment info for logging purposes
-        echo "Exec: $CMD" -- ${1+"$@"}
-        echo "Root: $ROOTDIR"
-
-        # Log the startup
-        logger -t "$SCRIPT[$$]" "Starting up"
-
-        # Start the VM
-        exec $CMD -- ${1+"$@"}
-        ;;
-
-    foreground)
-        # start up the release in the foreground for use by runit
-        # or other supervision services
-
-        BOOTFILE=$SCRIPT
-        FOREGROUNDOPTIONS="-noinput +Bd"
-
-        # Setup beam-required vars
-        ROOTDIR=$RUNNER_BASE_DIR
-        BINDIR=$ROOTDIR/erts-$ERTS_VSN/bin
-        EMU=beam
-        PROGNAME=`echo $0 | sed 's/.*\///'`
-        CMD="$BINDIR/erlexec $FOREGROUNDOPTIONS -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$BOOTFILE -config $CONFIG_PATH -args_file $VMARGS_PATH"
-        export EMU
-        export ROOTDIR
-        export BINDIR
-        export PROGNAME
-
-        # Dump environment info for logging purposes
-        echo "Exec: $CMD" -- ${1+"$@"}
-        echo "Root: $ROOTDIR"
-
-        # Start the VM
-        exec $CMD -- ${1+"$@"}
-        ;;
-    *)
-        echo "Usage: $SCRIPT {start|start_boot <file>|foreground|stop|restart|reboot|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade}"
+checkdupname()
+{
+    $ERL $ERL_NAME_ARG -s erlang halt |\
+        grep -c duplicate_name > /dev/null
+    if [ "$?" -eq 0 ]; then
+        echo "ERROR: Duplicate node name '$ERL_NAME' already running."
         exit 1
-        ;;
+    fi
+}
+
+checkstorage()
+{
+    $ERL 1> /dev/null <<EOF
+Exit = try
+    {ok, [P]} = file:consult("$OA_CONFIG_PATH"),
+    C = proplists:get_value(oacd_core, P),
+    true = (proplists:get_value(agent_auth_storage, C) =/= undefined),
+    true = (proplists:get_value(call_queue_config_storage, C) =/= undefined),
+    0
+catch _:_ ->
+    1
+end,
+halt(Exit).
+EOF
+    if [ "$?" -eq 1 ]; then
+        echo "ERROR: agent_auth_storage and call_queue_storage must be defined in \"$OA_CONFIG_PATH\""
+        exit 1
+    fi
+}
+
+case $ARGS in
+    ' status' ) start ;;
+    ' start' ) start ;;
+    ' live' ) live ;;
+    * ) usage ;;
 esac
 
 exit 0
